### ISSUE TITLE
Calculating genome-wide correlation matrix for new LD reference 

### ISSUE THREAD

**Issue by Janina24** [privefl/paper-ldpred2#13]
Dear Dr. Privé, 
I´m trying to work with the newly provided LD reference data.

The example code from your tutorial works well when using the HapMap3 variants with LD blocks calculating corr_chr. How has this code to be adjusted when using the new HapMap+ variants (only a genome-wide .map file available)

```r
for (chr in 1:22) {

  cat(chr, ".. ", sep = "")

  ## indices in 'df_beta'
  ind.chr <- which(df_beta$chr == chr)
  ## indices in 'map_ldref'
  ind.chr2 <- df_beta$`_NUM_ID_`[ind.chr]
  ## indices in 'corr_chr'
  ind.chr3 <- match(ind.chr2, which(map_ldref$chr == chr))

  **corr_chr <- readRDS(paste0("ld-ref/LD_chr", chr, ".rds"))[ind.chr3, ind.chr3]**

  if (chr == 1) {
    corr <- as_SFBM(corr_chr, tmp)
  } else {
    corr$add_columns(corr_chr, nrow(corr))
  }
}
```
 
Thanks for your help!

**Comment by privefl** [comment]
I'll update the example script tomorrow morning.

**Comment by privefl** [comment]
Please check the new example R script from the tutorial.

**Comment by Janina24** [comment]
One more question: for this new set of HapMap3+ variants do I need the LD_with_blocks_chr.rds files used for previous HapMap variants?

**Comment by privefl** [comment]
Either the previous HapMap3 set, or the new HapMap3+, the code should not have to change.

**Comment by Janina24** [comment]
Thanks for your reply!
Always helpful :)
