### ISSUE TITLE
controlling for covariates

### ISSUE THREAD

**Issue by dev-dtorok** [privefl/paper-ldpred2#15]
Dear Florian!
I have a question related to controlling for covariates. For my analyses, I’m using a GWAS summary statistic where age, gender, and 10 principal components were added as covariates in the original analysis. After running LDPred2-auto on my independent population, I would like to calculate the R2 change as described here: [https://choishingwan.github.io/PRS-Tutorial/ldpred/]
My question is, is it correct to control for age, gender, and principal components calculated for my population, when I'm calculating the R2 change caused by the PRS? Isn’t it a problem that in the original GWAS the effect of the SNPs was already controlled for age and gender?
Sorry for the question, but I didn’t find any reference for that.
Thank you in advance,
Dora

**Comment by privefl** [comment]
Yes, I think it is correct, but you should not use the difference of R2, you should use a partial correlation (squared + keeping sign).

**Comment by privefl** [comment]
Also, please do not follow that tutorial, it is outdated.
Use https://privefl.github.io/bigsnpr/articles/LDpred2.html and https://privefl.github.io/bigsnpr-extdoc/polygenic-scores-pgs.html#example-ldpred2-and-lassosum2.

**Comment by dev-dtorok** [comment]
Thank you for your quick help!
