### ISSUE TITLE
GWAS sumstats without physical position and chromosome numbers

### ISSUE THREAD

**Issue by ghost** [privefl/paper-ldpred2#16]
Hi Florian,

Hope you are doing well! 

I am currently working on a project that involves the calculation of polygenic scores of multiple traits by LDpred2 for prediction.

However, external GWAS summary statistics are often heterogenous in terms of format, with some did not offer information on the physical position and chromosome numbers of the SNPs.
They did offer the RSID of the SNPs though.

Therefore, I am just wondering if we can still run LDpred2 without the physical positions (given that RSIDs are available) of the SNPs. Many thanks!

best wishes,
Chris

**Comment by privefl** [comment]
When using `snp_match()`, you can match by rsIDs instead of positions; there is such an example in the LDpred2 tutorial.

**Comment by ghost** [comment]
Many thanks on the reply!

Besides, just wondering about the formula in the imputation of effective N, which will be further utilized in LDpred2.

The previous preprint on effective N imputation (https://www.biorxiv.org/content/10.1101/2021.03.29.437510v4.full
) proposed the following formula:
![image](https://user-images.githubusercontent.com/124371734/217269273-263eba38-d31a-4902-aedb-f04bf1dc8760.png)

It was suggested when effective N is imputed by MAF and standard errors of SNPs, the variance of genotype term listed in the formula needs to be corrected by imputation INFO scores.

This would mean the imputation INFO score for a particular SNP decreases would cause an increase in the eventual sample size, which sounds a bit counterintuitive. 

Shall I correct the effect sizes / standard errors with INFO scores instead of the variance term?

Many thanks,
Chris

**Comment by privefl** [comment]
I guess it depends whether you want to estimate the sample size, or a "corrected" sample size (reduced with INFO score).

**Comment by ghost** [comment]
I am estimating the effective sample sizes that are not reported in some of the GWAS summary statistics, therefore I am using 2*MAF*(1-MAF)*INFO for estimating genotype variance.

When I tested this formula on a sample GWAS (with effective N already available), the imputed effective N seems to deviate more from the correct effective N as INFO score decreases.

This makes sense to a certain degree (lower imputation quality should lead to less precise estimations of effective N), it is still a bit confusing to me that the effective N actually increases when INFO score reduces, and cannot really account for this phenomenon.

**Comment by privefl** [comment]
Yes, I guess this is somewhat counter-intuitive.
Note that you should probably filter for small INFO scores beforehand.

**Comment by ghost** [comment]
Alright, many thanks on the clarification on the INFO score issue!
