### ISSUE TITLE
Combining chromosomes from .bed files

### ISSUE THREAD

**Issue by lizlitkowski** [privefl/paper-ldpred2#4]
Hi-

I am in the second stage of LDPred2 where I am bringing in the genotypes from a WGS and I would like to combine all the genotypes from 22 chromosomes into one big matrix to generate the predicted PRS.  I am using snp_readBed to read the individual chromosome .bed files but is there an R function to combine all the chromosomes together so that I can do one big matrix multiply using big_prodMat?

Thanks.
Liz

**Comment by privefl** [comment]
There are many ways you can do that:
- combine the bed files with PLINK (I think I talk about that in another issue here)
- compute 22 predictions (one for each chr) and sum them.
- you can also maybe directly compute the scores from bed files using PLINK (maybe using all 22 chrosomes with first point) or using `bigsnpr::bed_prodVec()` and combining all 22 scores.

**Comment by lizlitkowski** [comment]
Thanks for the options!  I had already tried the PLINK option but I was having trouble merging the files because the variant names seem to have fallen away after I used vcftools to extract my list of SNPs.  I was trying to avoid the second option but I know that one will work.  Thanks again.
