### ISSUE TITLE
Cholmod Error

### ISSUE THREAD

**Issue by dzimmerman-amc** [privefl/paper-ldpred2#9]
Hi there,

I am making use of .bgen files in the ldpred2 software which is around 22GB, I do have a large amounts of variants matched with my summary statistics as seen below:

#5,868,901 variants to be matched.
#892,483 ambiguous SNPs have been removed.
#4,965,936 variants have been matched; 0 were flipped and 2,689,301 were reversed.

When creating the on-disk sparse genome-wide correlation matrix on-the-fly I get the following error:

**Error in asMethod(object) :
  Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 89
Calls: <Anonymous> ... <Anonymous> -> .local -> as_gCsimpl -> as -> asMethod**

Is this because I do not have enough memory to run the correlation step? I seem to be stuck here and can't find a solution.

Thanks in advance!

Regards,
Dom

**Comment by privefl** [comment]
This issue has been reported multiple times here, please look at the other issues.
